GeniePrep/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_header = "GENIE Administrator"
admin.site.site_title = "GENIE Administrator"
admin.site.index_title = 'Welcome'

urlpatterns = [
    path('', include('account.urls')),
    path('practise/', include('practise.urls')),
    path('gniadmin/', admin.site.urls),
]

urlpatterns = urlpatterns + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cbt/urls.py
from django.urls import path
from .views import QuestionView, TestView

urlpatterns = [
    path('questions', view=QuestionView.as_view(), name="question"),
    path('tests', view=TestView.as_view(), name="test"),
]

genieprep2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('frontend.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('cbt/', include('cbt.urls')),
]

account/models.py
from django.db import models
from practise.models import Subjects

# Create your models here.
class Schools(models.Model):
    logo = models.ImageField(
        upload_to='schoolLogo', default='static/img/school_placeholder.jpg')
    name = models.CharField(max_length=100)
    short_name = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=False, auto_now=True)
    
    def __str__(self):
        return self.name

    class Meta:
        ordering = ('date_added')

    class Meta:
        db_table = "Schools_tb"
        verbose_name = "School"
        verbose_name_plural = "Schools"


class Courses(models.Model):
    name = models.CharField(max_length=100)
    short_name = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('date_added')

    class Meta:
        db_table = "courses_tb"
        verbose_name = "Course"
        verbose_name_plural = "Courses"


class Genie_Users(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    """
    SCHOOLS = (
        ('FUTA', 'Federal University Of Technology Akure'),
    )
    """
    genieID = models.CharField(max_length=30)
    profileimg = models.ImageField(
        upload_to='profilepics', default='/static/img/profile_placeholder.jpg')
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=20)

    username = models.CharField(max_length=20, null=False)
    password = models.CharField(max_length=100)

    subjects = models.ManyToManyField(Subjects)

    institution = models.ForeignKey(Schools, on_delete=models.CASCADE)
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)

    cutoff = models.CharField(max_length=20)
    jamb_score = models.CharField(max_length=20)
    asp_score = models.CharField(max_length=20)

    date_joined = models.DateTimeField(auto_now_add=False, auto_now=True)


    def __str__(self):
        return self.first_name + ' ' + self.last_name

    class Meta:
        ordering = ('date_joined')

    class Meta:
        db_table = "Users_tb"
        verbose_name = "Genie User"
        verbose_name_plural = "Genie Users"

practise/models.py
from django.db import models
#from account.models import Genie_Users

# Create your models here.


class Subjects(models.Model):
    """
    subjects = (
        ('MTH', 'Mathematics'),
        ('ENG', 'English'),
        ('PHY', 'Physics'),
        ('CHEM', 'Chemistry'),
        ('BIO', 'Biology'),
    )
    """
    code = models.CharField(max_length=20)
    name = models.CharField(max_length=100)
    short_name = models.CharField(max_length=30)
    date_added = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('date_added')

    class Meta:
        db_table = "Subjects_tb"
        verbose_name = "Subject"
        verbose_name_plural = "Subjects"



class TestLogs(models.Model):
    Uid = models.CharField(max_length=10, blank=False, null=False)
    #userid = models.ForeignKey(Genie_Users, on_delete=models.CASCADE)
    total_score_gotten = models.CharField(max_length=10, blank=True, null=True)
    total_max_score = models.CharField(max_length=10, blank=True, null=True)
    date_taken = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return str(self.date_taken)


    class Meta:
        ordering = ('date_taken')

    class Meta:
        db_table = "testLog_tb"
        verbose_name = "Test Log"
        verbose_name_plural = "Test Logs"


class TestScripts(models.Model):
    subject = models.ForeignKey(Subjects, on_delete=models.CASCADE)
    data = models.TextField()
    score = models.CharField(max_length=50)
    max_score = models.CharField(max_length=50)
    
    log = models.ForeignKey(TestLogs, on_delete=models.CASCADE)

    def calculatePercent(self):
        sc = TestScripts.objects.get(log=self.log, subject=self.subject)
        
        return (int(sc.score) / int(sc.log.total_max_score))

    percent = property(calculatePercent)
    
    class Meta:
        db_table = "testScripts_tb"
        verbose_name = "Test Script"
        verbose_name_plural = "Test Scripts"

templates/dashboard/dashmain.html
{% extends 'dashBase.html' %}{% load static %} {% block nav-content %}
<a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i>
        <img src="/media/{{user.profileimg}}" class="img-responsive img-circle visible-lg visible-md visible-sm" alt="Profile Image" width="30px" height="30px" style="border-radius: 50%;">
    </i>
</a>
<div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">

    <div class="dropdown-header">
        <small>Logged in as</small><br>
        <b>{{user.last_name}} {{user.first_name}}</b>
    </div>

    <div class="dropdown-divider"></div>

    <a class="dropdown-item" href="{% url 'practise' %}">Take a Test</a>

    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
</div>
{% endblock %} {% block content %}
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dash" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Overview</div>
                    <a class="nav-link" id="dash-btn" href="#dashboard">
                        <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                        Dashboard
                    </a>
                    <a class="nav-link" id="profile-btn" href="#profile">
                        <div class="sb-nav-link-icon"><i class="fas fa-user"></i></div>
                        Profile
                    </a>
                    <div class="sb-sidenav-menu-heading">Subjects</div>
                    <a class="nav-link collapsed" href="#subjects" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                        <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                        Subjects
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                            {% for subject in user.subjects.all %}
                            <p class="nav-link">{{subject.name}}</p>
                            {% endfor %}

                        </nav>
                    </div>
                    <!--
                        <a class="nav-link" id="target-btn" href="#target">
                        <div class="sb-nav-link-icon"><i class="fas fa-bullseye"></i></div>
                        Target Store
                        </a>
                    -->

                    <div class="sb-sidenav-menu-heading">Records</div>
                    <a class="nav-link" id="record-btn" href="#record">
                        <div class="sb-nav-link-icon"><i class="fas fa-history"></i></div>
                        Practise Records
                    </a>
                    <!--<a class="nav-link" id="leaderboard-btn" href="#leaderboard">
                        <div class="sb-nav-link-icon"><i class="fas fa-trophy"></i></div>
                        Leaderboard
                    </a>-->
                    <a class="nav-link" href="/">
                        <div class="sb-nav-link-icon"><i class="fas fa-sign-out-alt"></i></div>
                        logout
                    </a>

                </div>
            </div>
            <div class="sb-sidenav-footer-dash">
                <div class="small">Logged in as:</div>
                {{user.first_name}} {{user.last_name}}
            </div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <div id="dashy">
                    <!-- Breadcrumb -->
                    <h1 class="mt-4">Dashboard</h1>
                    <hr>
                    <nav aria-label="breadcrumb" class="main-breadcrumb">
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item active">Welcome! {{user.first_name}}</li>

                        </ol>
                    </nav>
                    <!-- /Breadcrumb -->


                    <h5 class="text-muted">Your Subjects</h5>
                    <div class="row">
                        {% for sub in user.subjects.all %}
                        <div class="col-xl-3 col-md-6">
                            <div class="card bg-primary text-white mb-4">
                                <div class="card-body">{{sub.name}}</div>
                                <div class="card-footer d-flex align-items-center justify-content-between">
                                    <a class="small text-white stretched-link" href="#">View Details</a>
                                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                </div>
                            </div>
                        </div>
                        {% endfor %} {% comment %}
                        <div class="col-xl-3 col-md-6">
                            <div class="card bg-primary text-white mb-4">
                                <div class="card-body">English</div>
                                <div class="card-footer d-flex align-items-center justify-content-between">
                                    <a class="small text-white stretched-link" href="#">View Details</a>
                                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-3 col-md-6">
                            <div class="card bg-warning text-white mb-4">
                                <div class="card-body">Mathematics</div>
                                <div class="card-footer d-flex align-items-center justify-content-between">
                                    <a class="small text-white stretched-link" href="#">View Details</a>
                                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-3 col-md-6">
                            <div class="card bg-success text-white mb-4">
                                <div class="card-body">Physics</div>
                                <div class="card-footer d-flex align-items-center justify-content-between">
                                    <a class="small text-white stretched-link" href="#">View Details</a>
                                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-3 col-md-6">
                            <div class="card bg-danger text-white mb-4">
                                <div class="card-body">Chemistry</div>
                                <div class="card-footer d-flex align-items-center justify-content-between">
                                    <a class="small text-white stretched-link" href="#">View Details</a>
                                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                </div>
                            </div>
                        </div>
                        {% endcomment %}
                    </div>


                    <div class="row text-center mb-5 mt-0">
                        <!-- <div class="col">
                            <button class="btn btn-info">Take Live test</button>
                        </div> -->
                        <div class="col">
                            <a class="btn btn-success" href="{% url 'practise' %}">Take Practise test</a>
                        </div>
                    </div>

                    {% comment %}
                    <div class="row">
                        <div class="col-xl-6">
                            <div class="card mb-4">
                                <div class="card-header">
                                    <i class="fas fa-chart-area mr-1"></i> Performace Area Chart
                                </div>
                                <div class="card-body"><canvas id="myAreaChart" width="100%" height="40"></canvas></div>
                            </div>
                        </div>
                        <div class="col-xl-6">
                            <div class="card mb-4">
                                <div class="card-header">
                                    <i class="fas fa-chart-bar mr-1"></i> Performance Bar Chart Example
                                </div>
                                <div class="card-body"><canvas id="myBarChart" width="100%" height="40"></canvas></div>
                            </div>
                        </div>
                    </div>
                    {% endcomment %}


                    <div class="card mb-4">
                        <div class="card-header">
                            <i class="fas fa-table mr-1"></i> Practise Records
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Date</th>
                                            <th>Subjects taken</th>

                                            <th>Score</th>
                                            <th>View</th>
                                        </tr>
                                    </thead>
                                    <!-- 
                                    <tfoot>
                                        <tr>
                                            <th>Date</th>
                                            <th colspan="2">Subjects taken</th>
                                            <th>Score</th>
                                            <th></th>
                                        </tr>
                                    </tfoot> -->

                                    <tbody>
                                        {% for record in records %}
                                        <tr>
                                            <td>{{record.date_taken}}</td>
                                            <td>{% for sub in record.testscripts_set.all %}{{sub.subject.name}}, {% endfor %}</td>
                                            <td>{{record.total_score_gotten}}/{{record.total_max_score}}</td>
                                            <td><a href="javascript: window.location.href='/practise/result?t={{record.id}}'" class="btn btn-primary"><i class="fas fa-eye"></i></a></td>

                                        </tr>
                                        {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="content">

                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; 2021 Genie.inc</div>
                    <div>
                        <span>FUTA &middot;
                        POST UTME &amp; Practise</span>
                    </div>
                </div>
            </div>
        </footer>
    </div>
</div>
{% endblock %}

templates/dashboard/profile.html
{% load static %} {% static 'assets/images' as baseUrl %}
<!-- Breadcrumb -->
<h1 class="mt-4">Profile</h1>
<hr>
<nav aria-label="breadcrumb" class="main-breadcrumb">
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active">Dashboard</li>
        <li class="breadcrumb-item active" aria-current="page">Profile</li>
    </ol>
</nav>
<!-- /Breadcrumb -->
<div class="main-body">

    <div class="row gutters-sm">
        <div class="col-md-4 mb-3">
            <!-- 1st card -->
            <div class="card">
                <div class="card-body">
                    <div class="d-flex flex-column align-items-center text-center">
                        <img src="/media/{{user.profileimg}}" alt="Profile Picture" class="rounded-circle" width="150">
                        <div class="mt-3">
                            <h4>{{user.last_name}} {{user.first_name}}</h4>
                            <p class="text-secondary small mb-1">Genie ID: {{user.genieID}}</p>
                            <p class="text-secondary mb-1">username: {{user.username}}</p>
                            <!--<p class="text-muted font-size-sm">{{user.email}}</p>-->

                            <button class="btn btn-outline-primary">Edit Profile</button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /1st card-->

            <!-- 2nd card-->
            <div class="card mt-3">
                <h3 class="text-muted text-left m-3">School you aspire</h3>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item d-flex justify-content-center align-items-center flex-wrap">
                        <img src="/media/{{user.institution.logo}}" class="img-responsive img-circle center-block" alt="Subject-Tab">
                        <span class="h6"><b></strong>{{user.institution.name}}</b></span>
                    </li>

                    <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">

                        <span class="text-secondary"><p>Federal University of Technology, Akure (FUTA), a top ranking University of technology in Nigeria and indeed the nation's pride. Established in 1981.</p></span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                        <h6 class="mb-0">
                            Course:
                        </h6>
                        <span class="text-secondary">{{user.course}}</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                        <h6 class="mb-0">Cutoff:</h6>
                        <span class="text-secondary">{{user.cutoff}} points</span>
                    </li>

                </ul>
            </div>
            <!-- /2nd card-->
        </div>

        <div class="col-md-8">
            <div class="card mb-3">
                <!-- 3rd card -->
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Full Name</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {{user.last_name}} {{user.first_name}}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Email</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {{user.email}}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Phone</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {{user.phone_number}}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Gender</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {{user.get_gender_display}}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Jamb Score</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {{user.jamb_score}}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3 col-xs-3">
                            <h6 class="mb-0">Password</h6>
                        </div>
                        <div class="col-sm-3 col-xs-3 text-secondary">

                            <input type="password" value="{{user.password}}" disabled/>

                        </div>
                        <div class="col-sm-3 col-xs-3 ml-3 text-secondary">

                            <button class="btn btn-primary btn-sm">Change</button>

                        </div>
                    </div>
                </div>
                <!-- /3rd card -->
            </div>
            <div class="row gutters-sm">
                <!-- 4th card -->
                <div class="col-sm-6 mb-3">
                    <div class="card h-100">
                        <div class="card-body">
                            <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">Post Utme</i>Subjects</h6>
                            <!--
                                <ul class="list-group list-group-flush">
                                <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                    <h6 class="mb-0">
                                        English
                                    </h6>
                                    <span class="text-secondary">Max questions:6</span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                    <h6 class="mb-0">
                                        Mathematics
                                    </h6>
                                    <span class="text-secondary">Max questions:6</span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                    <h6 class="mb-0">
                                        Physics
                                    </h6>
                                    <span class="text-secondary">Max questions:6</span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                    <h6 class="mb-0">Chemistry</h6>
                                    <span class="text-secondary">Max questions:6</span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                    <h6 class="mb-0">Total Futa PUTME Questions</h6>
                                    <span class="text-secondary">24</span>
                                </li>

                                <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                    <h6 class="mb-0">Minimum to score</h6>
                                    <span class="text-secondary">12/24 (50%)</span>
                                </li>

                            </ul>-->
                            <div class="row align-items-center">
                                <h4 class="text-center text-muted my-5">This Feature is Under Construction</h4>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /4th card -->

                <div class="col-sm-6 mb-3">
                    <div class="card h-100">
                        <div class="card-body">
                            <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">Post UTME</i>Target & Plan</h6>
                            <!--
                                <ul class="list-group list-group-flush">
                                <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                    <h6 class="mb-0">
                                        English
                                    </h6>
                                    <span class="text-secondary">Target: 6</span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                    <h6 class="mb-0">
                                        Mathematics
                                    </h6>
                                    <span class="text-secondary">Target: 6</span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                    <h6 class="mb-0">
                                        Physics
                                    </h6>
                                    <span class="text-secondary">Target: 6</span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                    <h6 class="mb-0">Chemistry</h6>
                                    <span class="text-secondary">Target: 6</span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                    <h6 class="mb-0">Total score</h6>
                                    <span class="text-secondary">24/24 (100%)</span>
                                </li>

                                <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                    <h6 class="mb-0">Point acquired</h6>
                                    <span class="text-secondary">82.75 points</span>
                                </li>

                            </ul>
                            <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">Genie Remark</i>Great!😎</h6>
                        -->
                            <div class="row align-items-center">
                                <h4 class="text-center text-muted my-5">This Feature is Under Construction</h4>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

templates/dashboard/records.html
<!-- Breadcrumb -->
<h1 class="mt-4">Practise Records</h1>
<hr>
<nav aria-label="breadcrumb" class="main-breadcrumb">
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active">Dashboard / history</li>

    </ol>
</nav>
<!-- /Breadcrumb -->

<!-- Chart-->
{% comment %}
<div class="row">
    <div class="col-xl-6">
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-chart-area mr-1"></i> Performace Area Chart
            </div>
            <div class="card-body"><canvas id="myAreaChart" width="100%" height="40"></canvas></div>
        </div>
    </div>
    <div class="col-xl-6">
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-chart-bar mr-1"></i> Performance Bar Chart Example
            </div>
            <div class="card-body"><canvas id="myBarChart" width="100%" height="40"></canvas></div>
        </div>
    </div>
</div>
{% endcomment %}


<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table mr-1"></i> Your Practise Records
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Subjects taken</th>

                        <th>Score</th>
                        <th>View</th>
                    </tr>
                </thead>


                <tbody>
                    {% for record in records %}
                    <tr>
                        <td>{{record.date_taken}}</td>
                        <td>{% for sub in record.testscripts_set.all %}{{sub.subject.name}}, {% endfor %}</td>
                        <td>{{record.total_score_gotten}}/{{record.total_max_score}}</td>
                        <td><a href="javascript: window.location.href='/practise/result?t={{record.id}}'" class="btn btn-primary"><i class="fas fa-eye"></i></a></td>

                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
</div>